---
title: Mobilon
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:path"
  phones:
    title: Phones
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: phones
  values:
    layout: phone
    Brand: 
    Is in stock: 
    Is in sale: 
    Thumbnail image: 
    price: 
    old price: 
    camera: 
    selfie camera: 
    memory: 
    processor: 
    ram: 
    screen type: 
    screen size: 
    battery: 
    year: 
    images:
    - 
cats:
- apple
- samsung
author: Revaz Zakalashvili
tagline: Used Mobile Phones
description: 
keywords: 
email: contact@mobilon.ge
facebook: https://www.facebook.com/mobilon.ge/
repository: mobilon/revazi
baseurl: 
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
